name: trigger-binder-build

on:
  workflow_run:
    workflows: [populate-branches]
    types:
      - completed

jobs:
  trigger-binder-build:
    runs-on: ubuntu-latest
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1
        with:
          target-repo: ${{ github.repository }}
          service-name: gh
          target-state: binder
          use-default-build-servers: true
          debug: false
